# Generated by Django 2.2.7 on 2019-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
