# Generated by Django 2.2.7 on 2019-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrip', '0002_festa'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='tag',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
